/* This file is automatically generated */
#pragma once
enum KoopaSymbol {
  STOMP,
  FIREBALL,
  HIT_WALL_LEFT,
  HIT_WALL_RIGHT,
  KICKED_FROM_LEFT,
  KICKED_FROM_RIGHT,
  TIMER_EXPIRED,
  NR_KoopaSymbol
};
enum KoopaState {
  WALKING_LEFT,
  WALKING_RIGHT,
  HIDING_IN_SHELL,
  ROLLING_LEFT,
  ROLLING_RIGHT,
  DEAD,
  NR_KoopaState
};
extern FsmInfo<KoopaSymbol, KoopaState> koopa_graph;
void init();

