/* This file is automatically generated */
typedef KoopaSymbol SClass;
typedef KoopaState TClass;
static Node<SClass, TClass> node_WALKING_LEFT = {
  .name = WALKING_LEFT, .n_edges = 3, .out_edges = nullptr
};
static Node<SClass, TClass> node_WALKING_RIGHT = {
  .name = WALKING_RIGHT, .n_edges = 3, .out_edges = nullptr
};
static Node<SClass, TClass> node_HIDING_IN_SHELL = {
  .name = HIDING_IN_SHELL, .n_edges = 4, .out_edges = nullptr
};
static Node<SClass, TClass> node_ROLLING_LEFT = {
  .name = ROLLING_LEFT, .n_edges = 3, .out_edges = nullptr
};
static Node<SClass, TClass> node_ROLLING_RIGHT = {
  .name = ROLLING_RIGHT, .n_edges = 3, .out_edges = nullptr
};
static Node<SClass, TClass> node_DEAD = {
  .name = DEAD, .n_edges = 0, .out_edges = nullptr
};
/* Each out_* array's content is sorted by the input field's
   numeric value */
static Edge<SClass, TClass> out_WALKING_LEFT[] = {
  {.input = STOMP, .next = &node_HIDING_IN_SHELL},
  {.input = FIREBALL, .next = &node_DEAD},
  {.input = HIT_WALL_LEFT, .next = &node_WALKING_RIGHT},
};
static Edge<SClass, TClass> out_WALKING_RIGHT[] = {
  {.input = STOMP, .next = &node_HIDING_IN_SHELL},
  {.input = FIREBALL, .next = &node_DEAD},
  {.input = HIT_WALL_RIGHT, .next = &node_WALKING_LEFT},
};
static Edge<SClass, TClass> out_HIDING_IN_SHELL[] = {
  {.input = FIREBALL, .next = &node_DEAD},
  {.input = KICKED_FROM_LEFT, .next = &node_ROLLING_RIGHT},
  {.input = KICKED_FROM_RIGHT, .next = &node_ROLLING_LEFT},
  {.input = TIMER_EXPIRED, .next = &node_WALKING_LEFT},
};
static Edge<SClass, TClass> out_ROLLING_LEFT[] = {
  {.input = STOMP, .next = &node_HIDING_IN_SHELL},
  {.input = FIREBALL, .next = &node_DEAD},
  {.input = HIT_WALL_LEFT, .next = &node_ROLLING_RIGHT},
};
static Edge<SClass, TClass> out_ROLLING_RIGHT[] = {
  {.input = STOMP, .next = &node_HIDING_IN_SHELL},
  {.input = FIREBALL, .next = &node_DEAD},
  {.input = HIT_WALL_RIGHT, .next = &node_ROLLING_LEFT},
};
static bool initialized = false;
void init() {
  if (initialized) return;
  node_WALKING_LEFT.out_edges = &(out_WALKING_LEFT[0]);
  node_WALKING_RIGHT.out_edges = &(out_WALKING_RIGHT[0]);
  node_HIDING_IN_SHELL.out_edges = &(out_HIDING_IN_SHELL[0]);
  node_ROLLING_LEFT.out_edges = &(out_ROLLING_LEFT[0]);
  node_ROLLING_RIGHT.out_edges = &(out_ROLLING_RIGHT[0]);
  /* The node DEAD does not have any out-arrows */
  initialized = true;
};
Node<SClass, TClass>* array_koopa_graph[] = {
  &node_WALKING_LEFT,
  &node_WALKING_RIGHT,
  &node_HIDING_IN_SHELL,
  &node_ROLLING_LEFT,
  &node_ROLLING_RIGHT,
  &node_DEAD,
  nullptr
};
FsmInfo<SClass, TClass> koopa_graph = {
  .length = 6,
  .nodes = &(array_koopa_graph[0]),
  .initial = &node_WALKING_LEFT
};
